// src/App.tsx
import type { Component } from "solid-js";
import { For } from "solid-js";
import { store } from "./store";

function onHost() {
  window.navigator.clipboard.writeText(store.getId());
}

function onJoin() {
  const peer = prompt("peer");
  if (peer) store.addConnection(peer);
}

const App: Component = () => {
  return (
    <>
      <header>
        <details open>
          <summary>
            {store.getId()} ({store.getPeers().length})
          </summary>
          <ul>
            <For each={store.getPeers()}>{(peer) => <li>{peer}</li>}</For>
          </ul>
        </details>
      </header>
      <main>
        <menu>
          <li>
            <button onClick={onHost}>Host</button>
          </li>
          <li>
            <button onClick={onJoin}>Join</button>
          </li>
        </menu>

        <ol>
          <For each={store.getData()}>
            {(data) => (
              <li>
                <pre>{JSON.stringify(data, null, 2)}</pre>
              </li>
            )}
          </For>
        </ol>
      </main>
    </>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
  import { client, connections } from "./store.js";
  import { connectTo, initClient } from "./networking";
  import { onMount } from "svelte";

  onMount(initClient);

  function onHost() {
    window.navigator.clipboard.writeText($client.id);
  }

  function onJoin() {
    const peer = (prompt("peer") ?? "").trim();
    if (peer) connectTo(peer);
  }
</script>

<header>
  {#if $client}
    <span>{$client.id}</span>
  {/if}
</header>

<main>
  <menu>
    <li>
      <button on:click={onHost}>Host</button>
    </li>
    <li>
      <button on:click={onJoin}>Join</button>
    </li>
  </menu>
  <ol>
    {#each $connections as connection}
      <li>{connection.peer}</li>
    {:else}
      <li><em>No connections...</em></li>
    {/each}
  </ol>
</main>

<style lang="css">
</style>
